exec = require('child_process').exec
fs = require 'fs'

coffeekup = require 'coffeekup'

task 'build', ->
  
  fs.readFile 'templates.coffee', 'utf-8', (err, data) ->
  
    console.log err if err
    
    compiled = coffeekup.compile data
    
    str = String(compiled).replace 'function anonymous', 'function template'
    
    fs.writeFile '../../static/js/templates.js', str, (err) ->
        console.log err if err
